# Generated by Django 3.2.9 on 2022-07-13 09:49

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
